In [1]:
import numpy as np
import pandas as pd


In [52]:
board = [[9,2,6,3,4,0,7,0,1],
   [0,5,0,0,2,6,4,0,9],
   [0,7,0,8,0,1,0,0,0],
   [0,0,0,9,0,0,2,0,7],
   [3,4,2,0,0,0,0,0,5],
   [1,0,0,0,0,0,8,0,0],
   [6,8,5,4,0,0,0,1,2],
   [0,0,4,0,0,2,9,0,0],
   [0,1,0,5,3,8,0,7,0]]

def printq(bo):
    for i in range(len(bo)):
        if i%3==0 and i!=0:
            print('- - - - - - - - - -')

        for j in range(len(bo[0])):
            if j%3==0 and j!=0:
                print('|',end='')
            if j==8:
                print(bo[i][j])
            else:
                print(str(bo[i][j]),end=' ')
def empty_pos(bo):
    for i in range(len(bo)):
        for j in range(len(bo[0])):
            if bo[i][j]==0:
                return i,j
    return None
def valid(bo,num,pos):
    for i in range(len(bo[0])):
        if bo[pos[0]][i]== num and pos[1]!=i:
            return False
    # checking column
    for i in range(len(bo)):
        if bo[i][pos[1]]== num and pos[0]!=i:
            return False
    # checking box
              
    box_x=pos[0] //3
    box_y=pos[1]//3
    for i in range(box_y*3,box_y*3+3):
        for j in range(box_x*3,box_x*3+3):
            if bo[i][j]==num and (i,j)!=pos:
                return False

    return True

    
def solve(bo):
    find=empty_pos(bo)
    if not find:
        return True
    else:
        row,col=find
    for i in range(1,10):
        if valid(bo,i,(row,col)):
            bo[row][col]=i
            if solve(bo):
                
                return True
            bo[row][col]=0
    
    return False

solve(board)
board

[[9, 2, 6, 3, 4, 0, 7, 0, 1],
 [0, 5, 0, 0, 2, 6, 4, 0, 9],
 [0, 7, 0, 8, 0, 1, 0, 0, 0],
 [0, 0, 0, 9, 0, 0, 2, 0, 7],
 [3, 4, 2, 0, 0, 0, 0, 0, 5],
 [1, 0, 0, 0, 0, 0, 8, 0, 0],
 [6, 8, 5, 4, 0, 0, 0, 1, 2],
 [0, 0, 4, 0, 0, 2, 9, 0, 0],
 [0, 1, 0, 5, 3, 8, 0, 7, 0]]

In [3]:
import numpy as np
from itertools import permutations as pr

board = [[5,0,0,2,0,9,0,6,0],
   [0,6,2,7,3,0,0,9,8],
   [4,0,9,6,0,0,1,3,2],
   [9,0,0,0,0,0,4,0,7],
   [0,8,7,3,4,0,0,1,0],
   [2,0,0,1,0,0,0,0,3],
   [3,4,0,0,2,6,8,0,0],
   [0,0,6,0,5,1,0,0,0],
   [0,0,1,0,0,0,2,0,6]]
board=np.array(board)
orig_board=board

def tot_emp(board2):
    tot_emp_pos=[]
    for i in range(len(board2[0])):
        positions=[]
        for j in range(len(board2)):
            if board2[i][j]==0:
                pos=i,j

                positions.append(pos)
        tot_emp_pos.append(positions)
    return tot_emp_pos
tot_empty=tot_emp(orig_board)

def valids1(bo,num,pos):
    
    i =pos[0]
    j=pos[1]
    curr_row=bo[i]
    curr_col=bo[:,j]
    
  
    if i//3==0 and  j//3==0:curr_box=box(bo)[0]
    if i//3==0 and  j//3==1:curr_box=box(bo)[1] 
    if i//3==0 and  j//3==2:curr_box=box(bo)[2] 
    if i//3==1 and  j//3==0:curr_box=box(bo)[3] 
    if i//3==1 and  j//3==1:curr_box=box(bo)[4] 
    if i//3==1 and  j//3==2:curr_box=box(bo)[5] 
    if i//3==2 and  j//3==0:curr_box=box(bo)[6]
    if i//3==2 and  j//3==1:curr_box=box(bo)[7] 
    if i//3==2 and  j//3==2:curr_box=box(bo)[8]
        
    if num in curr_row or num in curr_col or num in curr_box:
        return False
    else:
        return True


def box(board1):
    x,y,k,l=0,0,0,0
    box=[]
    for i in range(0,3):
        for j in range(0,3):
            sxe=board1[x:k+3,y:l+3]
            
            l,y=l+3,y+3
            
            sxe=sxe.reshape(1,9)
            sxe=sxe[0].tolist()
            box.append(sxe)
        x,k=x+3,k+3
        y,l=0,0
    
    return(box)
def fil_row(row):
    
    f_row=[]
    for num in range(1,10):
        if num not in row:
            
            f_row.append(num)
    return(f_row)

bo=board
perm_box=[]

for i in range(0,9):
    empo=tot_empty[i]

    fi_row=fil_row(bo[i])
    per_box=[]
    perm_box.append(per_box)
    perm=pr(fi_row)
    for per in perm:
        l=0
        for num in per:

            if valids1(bo,num,(empo[l][0],empo[l][1]))==True:
                l+=1
            else:
                break
            if l==len(empo)-1:
                per_box.append(per)

                break

def solu(per,i):
    
    empo=tot_empty[i]
    g=0
    for d in range(len(per)):
        
            board[empo[g][0]][empo[g][1]]=0
            g+=1
    f=0
    
    for r in per:
        if valids1(board,r,(empo[f][0],empo[f][1]))==True:
            board[empo[f][0]][empo[f][1]]=r
            f+=1
    if f==len(empo):
        return True
    else:
        return False
def solr(i):
    for per0 in perm_box[i]:
        if solu(per0,i)==True:
            for per1 in perm_box[i+1]:
                if solu(per1,i+1)==True:
                    for per2 in perm_box[i+2]:
                        if solu(per2,i+2)==True:
                            for per3 in perm_box[i+3]:
                                if solu(per3,i+3)==True:
                                    for per4 in perm_box[i+4]:
                                        if solu(per4,i+4)==True:
                                            for per5 in perm_box[i+5]:
                                                if solu(per5,i+5)==True:
                                                    for per6 in perm_box[i+6]:
                                                        if solu(per6,i+6)==True:
                                                             for per7 in perm_box[i+7]:
                                                                if solu(per7,i+7)==True:
                                                                    for per8 in perm_box[i+8]:
                                                                        if solu(per8,i+8)==True:
                                                                            return board
            

            
                   
solr(0)   


array([[5, 3, 8, 2, 1, 9, 7, 6, 4],
       [1, 6, 2, 7, 3, 4, 5, 9, 8],
       [4, 7, 9, 6, 8, 5, 1, 3, 2],
       [9, 1, 3, 5, 6, 8, 4, 2, 7],
       [6, 8, 7, 3, 4, 2, 9, 1, 5],
       [2, 5, 4, 1, 9, 7, 6, 8, 3],
       [3, 4, 5, 9, 2, 6, 8, 7, 1],
       [7, 2, 6, 8, 5, 1, 3, 4, 9],
       [8, 9, 1, 4, 7, 3, 2, 5, 6]])

In [60]:
df=[[5,0,0,2,0,9,0,6,0],
   [0,6,2,7,3,0,0,9,8],
   [4,0,9,6,0,0,1,3,2],
   [9,0,0,0,0,0,4,0,7],
   [0,8,7,3,4,0,0,1,0],
   [2,0,0,1,0,0,0,0,3],
   [3,4,0,0,2,6,8,0,0],
   [0,0,6,0,5,1,0,0,0],
   [0,0,1,0,0,0,2,0,6]]

In [38]:
df=pd.read_csv('desktop/gdp.csv')
x=df.amount.sum()
x

34200

[[9 2 6 3 4 0 7 0 1]
 [0 5 0 0 2 6 4 0 9]
 [0 7 0 8 0 1 0 0 0]
 [0 0 0 9 0 0 2 0 7]
 [5 0 0 0 0 0 2 4 3]
 [1 0 0 0 0 0 8 0 0]
 [6 8 5 4 0 0 0 1 2]
 [0 0 4 0 0 2 9 0 0]
 [0 1 0 5 3 8 0 7 0]]


In [33]:
df1.shape

(9, 9)